# Default properties

spring:
  # Write timestamps in ISO format
  jackson.serialization.write-dates-as-timestamps: false

  # Use the enhanced (non-deprecated) sequence generator
  jpa.properties.hibernate.id.new_generator_mappings: true

# Actuator info
info.app:
  name: @project.name@
  description: @project.description@
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@
