# Default properties

spring:
  # Write timestamps in ISO format
  jackson.serialization.write-dates-as-timestamps: false

  # Use the enhanced (non-deprecated) sequence generator
  jpa.properties.hibernate.id.new_generator_mappings: true

  application:
    name: @project.name@

  datasource.driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate.ddl-auto: validate

  cache.type: redis


# Actuator health and metrics
management:
  endpoints:
    web.exposure.include: health, info, metrics, flyway
  endpoint:
    health.show-details: always
  health:
    db.enabled: true
    redis.enabled: true
    diskspace.enabled: false

# Actuator info
info:
  project:
    name: @project.name@
    description: @project.description@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
  build:
    maven: @maven.version@
    time: @maven.build.timestamp@
    git:
      commit: @git.commit.id@
      describe: @git.commit.id.describe@
    system:
      user: @user.name@
      os: @os.name@/@os.arch@
    java:
      runtime: @java.runtime.name@
      vm: @java.vm.name@
      version: @java.version@
  runtime:
    spring:
      profile: ${spring.profiles.active:default}
    system:
      user: ${user.name}
      os: ${os.name}/${os.arch}
    java:
      runtime: ${java.runtime.name}
      vm: ${java.vm.name}
      version: ${java.version}

---
spring:
  profiles: local

logging.level:
  org.springframework:
    transaction.interceptor: TRACE
    security.web.csrf.CsrfFilter: DEBUG

---
spring:
  profiles: development

logging.level:
  org.springframework:
    transaction.interceptor: TRACE
    security.web.csrf.CsrfFilter: DEBUG

---
spring:
  profiles: staging

---
spring:
  profiles: production
