# Default properties

spring:
  # Write timestamps in ISO format
  jackson.serialization.write-dates-as-timestamps: false

  # Use the enhanced (non-deprecated) sequence generator
  jpa.properties.hibernate.id.new_generator_mappings: true


# Actuator health
management:
  endpoint.health.show-details: always
  health:
    db.enabled: true
    redis.enabled: true
    diskspace.enabled: false

# Actuator info
info.app:
  name: @project.name@
  description: @project.description@
  maven:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
  build:
    time: @maven.build.timestamp@
    user: @user.name@
    os: @os.name@/@os.arch@
    git:
      commit: @git.commit.id@
      describe: @git.commit.id.describe@
    java:
      runtime: @java.runtime.name@
      vm.name: @java.vm.name@
      version: @java.version@
