# Default properties

spring:
  # Write timestamps in ISO format
  jackson.serialization.write-dates-as-timestamps: false

  # Use the enhanced (non-deprecated) sequence generator
  jpa.properties.hibernate.id.new_generator_mappings: true


# Actuator health and metrics
management:
  endpoints:
    web.exposure.include: health, info, metrics
  endpoint:
    health.show-details: always
  health:
    db.enabled: true
    redis.enabled: true
    diskspace.enabled: false

# Actuator info
info:
  project:
    name: @project.name@
    description: @project.description@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
    spring:
      boot: @spring.boot.version@
      version: @spring.version@
  build:
    maven: @maven.version@
    time: @maven.build.timestamp@
    system:
      user: @user.name@
      os: @os.name@/@os.arch@
    git:
      commit: @git.commit.id@
      describe: @git.commit.id.describe@
    java:
      runtime: @java.runtime.name@
      vm: @java.vm.name@
      version: @java.version@
  runtime:
    system:
      user: ${user.name}
      os: ${os.name}/${os.arch}
    spring:
      profile: ${spring.profiles.active:default}
    java:
      runtime: ${java.runtime.name}
      vm: ${java.vm.name}
      version: ${java.version}
